// <auto-generated />
namespace ToBeImplemented.Infrastructure.EFContext.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class AddUserLastLoginDate_AddUserRegistrationDate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddUserLastLoginDate_AddUserRegistrationDate));
        
        string IMigrationMetadata.Id
        {
            get { return "201406052227190_AddUserLastLoginDate_AddUserRegistrationDate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
